# Generated by Django 4.2.1 on 2023-05-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(default="기본 제목", max_length=100),
        ),
    ]
