# Generated by Django 4.2.1 on 2023-05-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "talent",
            "0002_rename_user_cart_user_id_rename_user_product_user_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
