# Generated by Django 4.2.1 on 2023-05-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talent", "0003_alter_user_birth_alter_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
