# Generated by Django 4.2 on 2023-05-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talent", "0004_alter_user_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="thumbnail_image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
