<<<<<<< HEAD:miniproject/talent/migrations/0005_alter_product_thumbnail_image.py
# Generated by Django 4.2 on 2023-05-16 07:11
=======
# Generated by Django 4.2.1 on 2023-05-16 08:05
>>>>>>> 16db27a4e1146d94e4276aa3aef97cd32cd5087c:miniproject /talent/migrations/0005_alter_product_thumbnail_image.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talent", "0004_alter_user_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="thumbnail_image",
<<<<<<< HEAD:miniproject/talent/migrations/0005_alter_product_thumbnail_image.py
            field=models.ImageField(upload_to="images/"),
=======
            field=models.ImageField(null=True, upload_to=""),
>>>>>>> 16db27a4e1146d94e4276aa3aef97cd32cd5087c:miniproject /talent/migrations/0005_alter_product_thumbnail_image.py
        ),
    ]
