# Generated by Django 4.2.1 on 2023-05-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talent", "0005_alter_product_thumbnail_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together={("user_id", "product")},
        ),
    ]
