# Generated by Django 4.2.1 on 2023-05-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talent", "0004_alter_user_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="thumbnail_image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
